### ISSUE TITLE
Getting Errors When Trying to Lunch start_script_win.bat

### ISSUE THREAD

**Issue by Firelytical** [xyzjoey/automate-davinci-resolve#20]
Hi!
I have found your scripts in git hub and I'm interested on how the script works , and I want to test it out , but I can't , since every time I lunch start_script_win.bat it always gives me errors , I have tried and installed python version 3.6.8 and removed python version 3.11.5 , and I'm still getting errors (different errors then the other version).
I have already installed the requirements from install_requirements.bat (every time I tested it out I re installed the requirements)

Can you tell me what python version are you using , and is it related to the issue that I have?
The Error... (I'm On windows 10)
```
Setup virtual environment...

gui-win: commands[0]> python C:\Users\firef\Desktop\automate-davinci-resolve-master/main_gui.py
Traceback (most recent call last):
  File "C:\Users\firef\Desktop\automate-davinci-resolve-master/main_gui.py", line 1, in <module>
    from automate_davinci_resolve.app.app import App
  File "C:\Users\firef\Desktop\automate-davinci-resolve-master\src\automate_davinci_resolve\app\app.py", line 4, in <module>
    from .actions import (
  File "C:\Users\firef\Desktop\automate-davinci-resolve-master\src\automate_davinci_resolve\app\actions\auto_textplus_style.py", line 7, in <module>
    from ..settings import AppSettings
  File "C:\Users\firef\Desktop\automate-davinci-resolve-master\src\automate_davinci_resolve\app\settings.py", line 3, in <module>
    from pydantic import BaseSettings
  File "C:\Users\firef\Desktop\automate-davinci-resolve-master\.tox\gui-win\Lib\site-packages\pydantic\__init__.py", line 210, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\firef\Desktop\automate-davinci-resolve-master\.tox\gui-win\Lib\site-packages\pydantic\_migration.py", line 289, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.3/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.3/u/import-error
gui-win: exit 1 (0.39 seconds) C:\Users\firef\Desktop\automate-davinci-resolve-master> python C:\Users\firef\Desktop\automate-davinci-resolve-master/main_gui.py pid=12536
  gui-win: FAIL code 1 (0.50=setup[0.11]+cmd[0.39] seconds)
  evaluation failed :( (0.75 seconds)

C:\Users\firef\Desktop\automate-davinci-resolve-master>
```

**Comment by Firelytical** [comment]
Here is what I have tried :
I have tried installing pydintic-settings and replacing the line in settings.py:
```
from pydantic import BaseSettings 
to
from pydantic_settings import BaseSettings
```

didn't work 

I also tried to install older versions of pydintic so it includes the Settings , still no luck....

**Comment by xyzjoey** [comment]
hello, sorry realized your comment late! this error is related to pydantic v2 breaking changes
this commit https://github.com/xyzjoey/automate-davinci-resolve/commit/a898ce709dac6e96013cf4b5b74c96fe9ecd8a3b has downgraded pydantic to < 2.0.0, it would fixed your issue
